# SPDX-License-Identifier: MIT
# Meson cross-file for QEMU Zynq-7000 (FreeRTOS, Cortex-A9)
# Usage: meson setup <builddir> <srcdir> --cross-file <this-file>

[binaries]
c = 'arm-none-eabi-gcc'
ar = 'arm-none-eabi-ar'
strip = 'arm-none-eabi-strip'

[host_machine]
system = 'none'
cpu_family = 'arm'
cpu = 'cortex-a9'
endian = 'little'

[built-in options]
c_args = ['-march=armv7-a', '-mtune=cortex-a9', '-mfpu=vfpv3', '-mfloat-abi=softfp', '-mno-unaligned-access', '-ftree-vectorize', '-ffast-math', '-funwind-tables', '-fno-strict-aliasing']

[project options]
osal = 'freertos'
platform = 'zynq-a9'
