/*
 * Auto-generated by CMake — do not edit.
 * Zephyr platform equivalent of Meson-generated claw_gen_config.h.
 */

#ifndef CLAW_GEN_CONFIG_H
#define CLAW_GEN_CONFIG_H

#define RT_CLAW_VERSION "0.2.0-zephyr"

/* AI Engine (from environment: RTCLAW_AI_API_KEY, etc.) */
#define CONFIG_RTCLAW_AI_API_KEY "@RTCLAW_AI_API_KEY@"
#define CONFIG_RTCLAW_AI_API_URL "@RTCLAW_AI_API_URL@"
#define CONFIG_RTCLAW_AI_MODEL "@RTCLAW_AI_MODEL@"

#endif /* CLAW_GEN_CONFIG_H */
